title: लघुवासुदेवमननम्
chapters: वर्णकानि
author: वासुदेवेन्द्रः
default_class: vritti
source: "ocr"
gloss_types:
  - data_type: notes
    css_style: fine_print
    hideable: true
    hidden_by_default: false
header: |
   **सर्वतन्त्रस्वतन्त्राय सदात्माद्वैतवेदिने ।<br>
   श्रीमते शंकरार्याय वेदान्तगुरवे नमः ॥१॥<br>
   योऽवतीर्ण इहाचार्यरूपेण यतिनां मुदे ।<br>
   श्रीमन्नारायणं वन्दे तं हरिं करुणानिधिम् ॥२॥<br>
   मननाख्यं प्रकरणं वासुदेवयतीश्वरैः ।<br>
   रचितं विस्तरेणाद्य संग्रहेण प्रकाश्यते ॥३॥<br>
   बालानामुपकाराय मम विज्ञानसिद्धये ।<br>
   तत्र श्रीबालगोपालकृष्णः सन्निहितो भवेत् ॥४॥**
