title: विचारसागरः
chapters: तरङ्गाः
author: साधुश्रीनिश्चलदासः (श्रीवासुदेवब्रह्मेन्द्रसरस्वती)
default_class: mula
shloka_toc: false
source: "https://github.com/aupasana/vichara"
display_source: true
dict:
   folder: advaita
gloss_types:
  - data_type: mula
    css_style: flowing_text
    hideable: false
    hidden_by_default: false
  - data_type: tippani
    css_style: fine_print
    label: "ग्रन्थकारटिप्पणी" #use only if boxed
    boxed: open
    hideable: false
    hidden_by_default: false
  - data_type: notes
    css_style: fine_print
    label: "विचारलहरी" # use only for boxed (स्मरणिका/संलेखः/लेखिका/मनोगतम्)
    boxed: open
    hideable: true
    hidden_by_default: true
header: |
   **सुखं नित्यं स्वप्रकाशं व्यापकं नामरूपयोः।<br>
   अधिष्ठानं बुद्ध्यबोध्यं बुद्धेर्दृग्यत्तु निर्मलम् ॥१॥<br>
   अपारं सर्ववेदान्तवेद्यं प्रत्यक् परं महः।<br>
   तदेवाहं न मत्तोऽन्यदिति मे निश्चिता मतिः ॥२॥**
