title: श्रीमद्भगवद्गीता
author: भगवान् वेदव्यासः
order: 1
#ignore: true
chapters: "अध्यायाः (सभाष्यम्)"
shloka_highlight: true
source: ["gitasupersite.in"]
gloss_types:
  - data_type: bhashya
    css_style: flowing_text
    label: "भाष्यम्"
    hideable: false
    hidden_by_default: false
  - data_type: nolabel
    css_style: flowing_text
    hideable: false
    hidden_by_default: false
  - data_type: notes
    css_style: fine_print
    label: "स्मरणिका"
    label_from_attr: label
    hideable: true
    boxed: closed
    hidden_by_default: true
  - data_type: anandagiritika
    label: "आनन्दगिरिटीका"
    exclude_site: true
    css_style: fine_print
    hideable: true
    boxed: closed
    hidden_by_default: true
header: |
    <small>source: mixed (typed, gitasupersite.in)</small>
